# Generated by Django 5.1.2 on 2024-10-30 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, unique=True, verbose_name='Elemento')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'elemento',
                'verbose_name_plural': 'elementos',
                'db_table': 'Elemento',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('num_ficha', models.PositiveIntegerField(default=1, verbose_name='Ficha')),
                ('proyecto', models.CharField(default='', max_length=200, verbose_name='Proyecto')),
                ('descripcion', models.CharField(default='', max_length=500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'movimiento',
                'verbose_name_plural': 'movimientos',
                'db_table': 'Movimiento',
            },
        ),
        migrations.CreateModel(
            name='DetalleMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.elemento', verbose_name='Elemento')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.movimiento', verbose_name='Movimiento')),
            ],
            options={
                'verbose_name': 'detalle movimiento',
                'verbose_name_plural': 'detalles movimiento',
                'db_table': 'DetalleMovimiento',
            },
        ),
    ]
