# Generated by Django 5.1.2 on 2024-10-28 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, unique=True)),
                ('cantidad', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'elemento',
                'verbose_name_plural': 'elementos',
                'db_table': 'Elemento',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('num_ficha', models.PositiveIntegerField(null=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('proyecto', models.CharField(default='', max_length=200)),
                ('descripcion', models.CharField(default='', max_length=500)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='app.elemento')),
            ],
            options={
                'verbose_name': 'movimiento',
                'verbose_name_plural': 'movimientos',
                'db_table': 'Movimiento',
            },
        ),
    ]
