# Generated by Django 5.1.2 on 2024-10-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='num_ficha',
            field=models.PositiveIntegerField(null=True, verbose_name='Número de ficha'),
        ),
    ]
