# Generated by Django 5.1.2 on 2024-10-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_detallemovimiento_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallemovimiento',
            name='cantidad',
            field=models.PositiveIntegerField(null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='cantidad',
            field=models.PositiveIntegerField(null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='descripcion',
            field=models.CharField(max_length=500, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='num_ficha',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='Ficha'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='proyecto',
            field=models.CharField(max_length=200, null=True, verbose_name='Proyecto'),
        ),
    ]
