# Generated by Django 5.1.2 on 2024-10-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_producto_elemento_alter_elemento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='item',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
