# Generated by Django 5.1.2 on 2024-10-28 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_movimiento_num_ficha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='item',
            field=models.CharField(max_length=100, unique=True, verbose_name='Elemento'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='descripcion',
            field=models.CharField(default='', max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='elemento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='app.elemento', verbose_name='Elemento'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='proyecto',
            field=models.CharField(default='', max_length=200, verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10, verbose_name='Tipo de movimiento'),
        ),
    ]
