# Generated by Django 5.1.2 on 2024-10-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_elemento_cantidad_alter_elemento_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='item',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
