# Generated by Django 5.1.2 on 2024-10-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_detallemovimiento_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallemovimiento',
            options={'verbose_name': 'detalle_movimiento', 'verbose_name_plural': 'detalles_movimiento'},
        ),
    ]
