# Generated by Django 5.1.2 on 2024-10-29 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_movimiento_num_ficha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='tipo',
        ),
    ]
