# Generated by Django 5.1.2 on 2024-10-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_elemento_cantidad_alter_elemento_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='item',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
