# Generated by Django 5.1.3 on 2024-11-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_detallemovimiento_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='elemento',
            name='descripcion',
            field=models.CharField(max_length=500, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='aprendiz',
            field=models.CharField(max_length=200, null=True, verbose_name='Aprendiz'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='instructor',
            field=models.CharField(max_length=200, null=True, verbose_name='Instructor'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='num_aprendices',
            field=models.PositiveIntegerField(null=True, verbose_name='Número de aprendices'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='num_contrato',
            field=models.PositiveIntegerField(null=True, verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='obs_general',
            field=models.CharField(max_length=500, null=True, verbose_name='Observaciones generales'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='observaciones',
            field=models.CharField(max_length=500, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='programa_formacion',
            field=models.CharField(max_length=100, null=True, verbose_name='Programa de formación'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='saldo',
            field=models.PositiveIntegerField(null=True, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='item',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Elemento'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='num_ficha',
            field=models.PositiveIntegerField(null=True, verbose_name='Ficha'),
        ),
    ]
