# Generated by Django 5.1.2 on 2024-10-29 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_movimiento_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='elemento',
        ),
        migrations.CreateModel(
            name='detalle_movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='app.elemento', verbose_name='Elemento')),
            ],
            options={
                'verbose_name': 'detalle_movimiento',
                'verbose_name_plural': 'detalle_movimientos',
                'db_table': 'Detalle_movimiento',
            },
        ),
    ]
