# Generated by Django 5.1.3 on 2024-11-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_movimiento_descripcion_elemento_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='proyecto',
            field=models.CharField(max_length=200, null=True, verbose_name='Proyectos'),
        ),
    ]
