# Generated by Django 5.1.2 on 2024-10-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_elemento_descripcion_alter_elemento_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elemento',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
