# Generated by Django 5.1.2 on 2024-10-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_elemento_descripcion_movimiento_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
