# Generated by Django 5.1.3 on 2024-11-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_movimiento_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='elemento',
            name='observacion',
            field=models.CharField(max_length=500, null=True, verbose_name='Observaciones'),
        ),
    ]
