# Generated by Django 5.1.2 on 2024-10-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_movimiento_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='elemento',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
