# Generated by Django 5.1.3 on 2024-11-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_detalle_movimiento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='dependencia',
            field=models.CharField(help_text='Seleccione una opción.', max_length=200, null=True, verbose_name='Dependencia'),
        ),
    ]
