# Generated by Django 5.1.3 on 2024-11-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_movimiento_dependencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_movimiento',
            old_name='elemento',
            new_name='id_elemento',
        ),
        migrations.RenameField(
            model_name='detalle_movimiento',
            old_name='movimiento',
            new_name='id_movimiento',
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='dependencia',
            field=models.CharField(choices=[('Regular', 'Regular'), ('FIC', 'FIC')], max_length=200, null=True, verbose_name='Dependencia'),
        ),
    ]
