# Generated by Django 5.1.3 on 2024-11-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_movimiento_observaciones_elemento_observacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elemento',
            old_name='observacion',
            new_name='observaciones',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha_inicio_programa',
            field=models.DateField(null=True, verbose_name='Fecha de inicio del programa de formación'),
        ),
    ]
