# Generated by Django 5.1.3 on 2024-11-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_observacion_elemento_observaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='saldo',
        ),
        migrations.AddField(
            model_name='elemento',
            name='saldo',
            field=models.PositiveIntegerField(null=True, verbose_name='Saldo'),
        ),
    ]
