# Generated by Django 5.1.3 on 2024-11-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_movimiento_dependencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_movimiento',
            name='id_elemento',
        ),
        migrations.RemoveField(
            model_name='detalle_movimiento',
            name='id_movimiento',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cantidad_contratada',
            field=models.PositiveIntegerField(null=True, verbose_name='Cantidad contratada'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cantidad_recibida',
            field=models.PositiveIntegerField(null=True, verbose_name='Cantidad recibida'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='item',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Elemento'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='observaciones',
            field=models.CharField(max_length=500, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='unidad_medida',
            field=models.CharField(max_length=100, null=True, verbose_name='Unidad de medida'),
        ),
        migrations.DeleteModel(
            name='Elemento',
        ),
        migrations.DeleteModel(
            name='detalle_movimiento',
        ),
    ]
