# Generated by Django 5.1.3 on 2024-11-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_movimiento_saldo_elemento_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elemento',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='elemento',
            name='cantidad_contratada',
            field=models.PositiveIntegerField(null=True, verbose_name='Cantidad contratada'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='cantidad_recibida',
            field=models.PositiveIntegerField(null=True, verbose_name='Cantidad recibida'),
        ),
    ]
