# Generated by Django 5.1.3 on 2024-11-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_detalle_movimiento_id_elemento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='unidad_medida',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='descripcion',
            field=models.CharField(max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='saldo',
            field=models.PositiveIntegerField(null=True, verbose_name='Saldo pendiente de entrega'),
        ),
    ]
