# Generated by Django 5.1.3 on 2024-11-29 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_movimiento_unidad_medida_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='cantidad_contratada',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='cantidad_recibida',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='item',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='saldo',
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='obs_general',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones generales'),
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, verbose_name='Ítem')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('cantidad_recibida', models.PositiveIntegerField(verbose_name='Cantidad recibida')),
                ('cantidad_contratada', models.PositiveIntegerField(verbose_name='Cantidad contratada')),
                ('saldo', models.PositiveIntegerField(verbose_name='Saldo pendiente de entrega')),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='app.movimiento', verbose_name='Movimiento asociado')),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementos',
                'db_table': 'Elemento',
            },
        ),
    ]
