# Generated by Django 5.1.3 on 2024-11-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_movimiento_programa_formacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallemovimiento',
            name='cantidad_contratada',
        ),
        migrations.RemoveField(
            model_name='detallemovimiento',
            name='cantidad_recibida',
        ),
        migrations.RemoveField(
            model_name='detallemovimiento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='detallemovimiento',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='detallemovimiento',
            name='saldo',
        ),
        migrations.AddField(
            model_name='elemento',
            name='cantidad_contratada',
            field=models.PositiveIntegerField(null=True, verbose_name='Cantidad contratada'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='cantidad_recibida',
            field=models.PositiveIntegerField(null=True, verbose_name='Cantidad recibida'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='descripcion',
            field=models.CharField(max_length=500, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='observaciones',
            field=models.CharField(max_length=500, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='saldo',
            field=models.PositiveIntegerField(null=True, verbose_name='Saldo'),
        ),
    ]
