# Generated by Django 5.1.3 on 2024-11-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_movimiento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='obs_general',
            field=models.CharField(max_length=500, null=True, verbose_name='Observaciones generales'),
        ),
    ]
