# Generated by Django 5.1.3 on 2024-11-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_detallemovimiento_cantidad_contratada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallemovimiento',
            name='cantidad',
        ),
    ]
