# Generated by Django 5.1.3 on 2024-12-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_movimiento_programa_formacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elemento',
            name='item',
        ),
        migrations.AddField(
            model_name='elemento',
            name='nombre',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='cantidad_contratada',
            field=models.PositiveIntegerField(null=True, verbose_name='Cantidad contratada'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='cantidad_recibida',
            field=models.PositiveIntegerField(null=True, verbose_name='Cantidad recibida'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='descripcion',
            field=models.CharField(max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='observaciones',
            field=models.CharField(max_length=500, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='saldo',
            field=models.PositiveIntegerField(null=True, verbose_name='Saldo pendiente de entrega'),
        ),
    ]
