# Generated by Django 5.1.3 on 2024-12-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_elemento_item_elemento_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elemento',
            name='nombre',
        ),
    ]
