# Generated by Django 5.1.3 on 2024-12-04 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_elemento_cantidad_contratada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallemovimiento',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.movimiento'),
        ),
    ]
