# Generated by Django 5.1.3 on 2024-12-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_detallemovimiento_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallemovimiento',
            name='cantidad_contratada',
            field=models.PositiveIntegerField(null=True, verbose_name='Cantidad contratada'),
        ),
        migrations.AlterField(
            model_name='detallemovimiento',
            name='cantidad_recibida',
            field=models.PositiveIntegerField(null=True, verbose_name='Cantidad recibida'),
        ),
        migrations.AlterField(
            model_name='detallemovimiento',
            name='observaciones',
            field=models.TextField(null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='detallemovimiento',
            name='saldo',
            field=models.PositiveIntegerField(null=True, verbose_name='Saldo pendiente de entrega'),
        ),
    ]
