# Generated by Django 5.1.3 on 2024-12-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_detallemovimiento_cantidad_contratada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='cantidad',
            field=models.PositiveIntegerField(null=True, verbose_name='Cantidad'),
        ),
    ]
