# Generated by Django 5.1.4 on 2024-12-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_detallemovimiento_cantidad_contratada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallemovimiento',
            name='cantidad_contratada',
            field=models.PositiveIntegerField(null=True, verbose_name='Cantidad contratada'),
        ),
        migrations.AlterField(
            model_name='detallemovimiento',
            name='cantidad_recibida',
            field=models.PositiveIntegerField(null=True, verbose_name='Cantidad recibida'),
        ),
    ]
