# Generated by Django 5.1.6 on 2025-03-03 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_movimiento_programa_formacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallemovimiento',
            name='programa',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.programa', verbose_name='Programa'),
        ),
    ]
