# Generated by Django 5.1.7 on 2025-03-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_detallemovimiento_programa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='programa',
            field=models.CharField(max_length=200, null=True, verbose_name='Programa'),
        ),
    ]
