# Generated by Django 5.1.7 on 2025-03-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_programa_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='cantidad',
            field=models.PositiveIntegerField(null=True, verbose_name='Cantidad'),
        ),
    ]
