# Generated by Django 5.1.7 on 2025-03-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_elemento_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='descripcion',
            field=models.CharField(max_length=200, null=True, verbose_name='Elemento'),
        ),
    ]
