programas = [
    "Ope. en confección industrial de ropa exterior",
    "Ope. en excavadora y retroexcavador",
    "Ope. en manejo de máquinas de confección industrial para jean",
    "Ope. en maquinaria de confección industrial",
    "Técn. en análisis de muestras químicas",
    "Técn. en análisis químico de carbón y minerales",
    "Técn. en apoyo administrativo en salud",
    "Técn. en atención en incendios, rescates y otras emergencias",
    "Técn. en carpintería de aluminio",
    "Técn. en carpintería",
    "Técn. en construcción de edificaciones",
    "Técn. en construcción de redes de acueducto y alcantarillado",
    "Técn. en construcción de vías",
    "Técn. en construcciones livianas en seco",
    "Técn. en dibujo arquitectónico",
    "Técn. en diseño e integración de multimedia",
    "Técn. en elaboración de audiovisuales",
    "Técn. en elaboración de muebles",
    "Técn. en electromecánico de minería bajo tierra",
    "Técn. en fabricación de estructuras metálicas soldadas",
    "Técn. en fabricación de muebles contemporáneos y modulares",
    "Técn. en instalación de redes aéreas de energía eléctrica",
    "Técn. en instalación de redes internas de telecomunicaciones",
    "Técn. en instalación de redes",
    "Técn. en instalaciones eléctricas en baja tensión",
    "Técn. en instalaciones eléctricas residenciales",
    "Técn. en instrumentación industrial",
    "Técn. en laboratorio de suelos",
    "Técn. en manejo ambiental",
    "Técn. en mantenimiento de equipo pesado para infraestructura, minería y transporte",
    "Técn. en mantenimiento de equipos de cómputo",
    "Técn. en mantenimiento de motores gasolina y gas",
    "Técn. en mantenimiento e instalación de sistemas solares fotovoltaicos",
    "Técn. en mecánico de maquinaria industrial",
    "Técn. en monitoreo ambiental",
    "Técn. en operación de maquinaria pesada para excavación",
    "Técn. en operación y mantenimiento de sistemas de abastecimiento de agua para pequeñas comunidades",
    "Técn. en patronista escalador",
    "Técn. en producción de multimedia",
    "Técn. en programación de aplicaciones para dispositivos móviles",
    "Técn. en seguridad ocupacional",
    "Técn. en servicios y Operaciones microfinancieras",
    "Técn. en sistemas",
    "Técn. en soldadura en platina",
    "Técn. en tratamiento de agua",
    "Técn. en trazado corte y armado en láminas",
    "Técn. en trazado corte y conformado de productos metálicos",
    "Técn. en trazo corte en confección industrial",
    "Tnlgo. en actividad física",
    "Tnlgo. en análisis y desarrollo de sistemas de información",
    "Tnlgo. en análisis y desarrollo de software",
    "Tnlgo. en animación 3d",
    "Tnlgo. en automatización industrial",
    "Tnlgo. en confección industrial",
    "Tnlgo. en construcción",
    "Tnlgo. en control ambiental",
    "Tnlgo. en de construcción en edificaciones",
    "Tnlgo. en de desarrollo de medios gráficos visuales",
    "Tnlgo. en desarrollo de colecciones para la industria de la moda",
    "Tnlgo. en desarrollo de videojuegos",
    "Tnlgo. en desarrollo gráfico de proyectos de arquitectura e ingeniería",
    "Tnlgo. en diseño de productos industriales",
    "Tnlgo. en diseño de sistemas mecánicos",
    "Tnlgo. en diseño e integración de automatismos mecatrónicos",
    "Tnlgo. en diseño implementación y mantenimiento de sistemas de telecomunicaciones",
    "Tnlgo. en diseño industrial",
    "Tnlgo. en diseño para la comunicación gráfica",
    "Tnlgo. en diseño para la industria de la moda",
    "Tnlgo. en electricidad industrial",
    "Tnlgo. en formulación de proyectos",
    "Tnlgo. en gestión ciclo de vida del producto",
    "Tnlgo. en gestión de la producción industrial",
    "Tnlgo. en gestión de la seguridad y salud en el trabajo",
    "Tnlgo. en gestión de mercados",
    "Tnlgo. en gestión de proyectos de desarrollo económico y social",
    "Tnlgo. en gestión de redes de datos",
    "Tnlgo. en gestión del ciclo de vida del producto",
    "Tnlgo. en gestión integrada de la calidad, medio ambiente seguridad y salud ocupacional",
    "Tnlgo. en gestión logística",
    "Tnlgo. en implementación y mantenimiento de sistemas de instrumentación. procesos industriales",
    "Tnlgo. en levantamientos topográficos y georreferenciación",
    "Tnlgo. en logística del transporte",
    "Tnlgo. en manejo ambiental",
    "Tnlgo. en mantenimiento de equipos de cómputo, diseño e instalación de cableado estructurado",
    "Tnlgo. en mantenimiento eléctrico industrial",
    "Tnlgo. en mantenimiento electrónico e instrumental industrial",
    "Tnlgo. en mantenimiento equipos de cómputo y cableado",
    "Tnlgo. en mantenimiento mecatrónico en automotores",
    "Tnlgo. en obras civiles",
    "Tnlgo. en procesos de la industria química",
    "Tnlgo. en producción de contenidos animados para la simulación de procesos industriales",
    "Tnlgo. en producción de medios audiovisuales digitales",
    "Tnlgo. en producción multimedia",
    "Tnlgo. en química aplicada a la industria",
    "Tnlgo. en química industrial",
    "Tnlgo. en salud ocupacional",
    "Tnlgo. en seguridad industrial salud ocupacional y medio ambiente en la construcción",
    "Tnlgo. en sistemas integrados de gestión",
    "Tnlgo. en técnicas de desarrollo gráfico de proyectos de arquitectura e ingeniería",
    "Tnlgo. en técnicas de desarrollo gráfico de proyectos de construcción",
    "Tnlgo. en topografía"
]
